services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - VITE_API_PATH=http://host.docker.internal/api
      - VITE_SPRINGSECURITY_USERNAME=admin
      - VITE_SPRINGSECURITY_PASSWORD=L12345
      
