services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_PATH: http://localhost/api
        VITE_SPRINGSECURITY_USERNAME: admin
        VITE_SPRINGSECURITY_PASSWORD: L12345
    image: victorlcdpaula/web-blume
    ports:
      - "80:80"
    volumes:
      - .:/app
      
