services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - VITE_API_PATH=http://localhost/api/
      - VITE_SPRINGSECURITY_USERNAME=admin
      - VITE_SPRINGSECURITY_PASSWORD=L12345
      
