name: CI WEB NEOS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: build
        run: |
          docker-compose -f docker-compose.yml build
      - name: publish
        run: |
          docker login -u victorlcdpaula -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push victorlcdpaula/web-blume:latest